#!/usr/bin/env ansible-playbook
- hosts: termux,localhost
  connection: local
  gather_facts: false
  name: runit services setup
  tasks:
    - name: install termux-services
      ansible.builtin.apt:
        name: termux-services
        state: latest
    - name: install vsv
      # https://github.com/bahamas10/vsv
      community.general.cargo:
        name: vsv
        state: latest
    - name: setup redis
      block:
        - name: install redis
          ansible.builtin.apt:
            name: redis
            state: latest
        - name: setup redis runit service
          block:
            - name: "redis: make service log directory"
              tags: [redis]
              ansible.builtin.file:
                path: "$PREFIX/var/service/redis/log"
                state: directory
                recurse: true
            - name: "redis: symlink log to svlogger"
              tags: [redis]
              ansible.builtin.file:
                src: $PREFIX/share/termux-services/svlogger
                dest: $PREFIX/var/service/redis/log/run
                state: link
            - name: "redis: create run script"
              tags: [redis]
              ansible.builtin.copy:
                content: "#!/bin/sh"
                mode: '0755'
                force: false
                dest: $PREFIX/var/service/redis/run
            - name: "redis: write service script"
              tags: [redis]
              ansible.builtin.blockinfile:
                dest: $PREFIX/var/service/redis/run
                marker: "# {mark} ansible managed runit service"
                block: |
                  exec redis-server $PREFIX/etc/redis.conf \
                    --bind 0.0.0.0 \
                    --ignore-warnings ARM64-COW-BUG \
                    --protected-mode no \
                    2>&1
            - name: "redis: enable service"
              tags: [redis, redis_quick]
              ansible.builtin.command: vsv enable redis
              register: redoutt
              changed_when: redoutt.rc != 0
            - name: "redis: restart service"
              tags: [redis, redis_quick]
              ansible.builtin.command: vsv restart redis
              changed_when: false
    - name: setup serf
      block:
        - name: check if serf exists
          tags: [serf]
          ansible.builtin.shell: command -v serf
          register: serfexists
          changed_when: false
        - name: install serf
          tags: [serf]
          when: "serfexists.rc != 0"
          ansible.builtin.command: go install -ldflags="-w -s" github.com/hashicorp/serf/cmd/serf@master
        - name: "serf: setup runit service and config"
          block:
            - name: "serf: make service log directory"
              tags: [serf]
              ansible.builtin.file:
                path: "$PREFIX/var/service/serf/log"
                state: directory
                recurse: true
            - name: "serf: symlink log to svlogger"
              tags: [serf]
              ansible.builtin.file:
                src: $PREFIX/share/termux-services/svlogger
                dest: $PREFIX/var/service/serf/log/run
                state: link
            - name: "serf: mkdir scripts dir"
              tags: [serf]
              ansible.builtin.file:
                path: $HOME/.config/serf/scripts
                recurse: true
                state: directory
            - name: "serf: write config"
              register: config_copy_res
              tags: [serf, serf_quick]
              ansible.builtin.copy:
                dest: $HOME/.config/serf/config.json
                mode: '644'
                force: true
                content: |
                  {
                    "discover": "swarm",
                    "node_name": "termux",
                    "event_handlers": [
                      "~/.config/serf/scripts/handler"
                    ],
                    "bind": "0.0.0.0:7946",
                    "rpc_addr": "0.0.0.0:7373",
                    "snapshot_path": "/data/data/com.termux/files/home/.config/serf/snapshot.snap",
                    "rejoin_after_leave": true,
                    "tombstone_timeout": "10m",
                    "tags_file": "/data/data/com.termux/files/home/.config/serf/tags.json",
                    "log_level": "debug"
                  }
            # - name: TODO copy serf handler script from dotfiles
            - name: "serf: create run script"
              tags: [serf]
              ansible.builtin.copy:
                content: "#!/bin/sh"
                mode: '0755'
                force: false
                dest: $PREFIX/var/service/serf/run
            - name: "serf: write run service script"
              tags: [serf]
              ansible.builtin.blockinfile:
                dest: $PREFIX/var/service/serf/run
                marker: "# {mark} ansible managed runit service"
                block: |
                  exec serf agent \
                    -config-file=$HOME/.config/serf/config.json
            - name: "serf: enable service"
              tags: [serf, serf_quick]
              ansible.builtin.command: vsv enable serf
              register: serfoutt
              changed_when: serfoutt.rc != 0
            - name: "serf: restart service"
              tags: [serf, serf_quick]
              when: config_copy_res.changed
              ansible.builtin.command: vsv restart serf
              changed_when: false
              # TODO move this rpc-addr into an env var SERF_RPC_ADDR
            - name: "serf: set tags"
              tags: [serf, serf_quick]
              vars:
                # TODO use as a yaml and auto alphabetic order it and get this format
                # TODO think of the externally set tags and not overwriting them
                # TODO remove tags that don't exist in the serf_tags
                # TODO(*) use a custom query host-capablilites to get these instead of tags
                serf_tags: "class=termux"
              block:
                - name: "serf: get existing tags"
                  changed_when: false
                  register: existing_tags
                  ansible.builtin.shell: |
                    serf info -rpc-addr=0.0.0.0:7373 -format=json \
                    | jq -r '.tags | to_entries | map("\(.key)=\(.value|tostring)") | join(" ")'
                - name: "serf: set tags for termux"
                  ansible.builtin.shell: |
                    echo {{ serf_tags }} \
                    | xargs -n 1 serf tags -rpc-addr=0.0.0.0:7373 -set
                  when: "serf_tags != existing_tags.stdout"

